config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # # root "posts#index"
  # resources :bookings, path: "/cars/:car_id/booking/new", except: :index
  # resources :bookings, path: "/host/:user_id", only: [:index, :show, :edit, :update]
  # resources :cars do
  #   resources :bookings, only: :new
  # end
  # root "posts#index"
  resources :users do
    resources :cars do
      resources :bookings, except: :index
    end
    resources :bookings, only: :index
    # resources :cars
  end
  resources :cars, only: [:index, :show, :destroy] do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :start_date, :end_date, presence: true
end

app/models/car.rb
class Car < ApplicationRecord
  # GeoCoding
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # Associations
  belongs_to :user
  has_many :bookings
  has_many_attached :photos

  # Validations
  validates :address, presence: true
  # validates :address, format: { with: /[\w\s]+, [0-9]+, [\w\s]+, \w+, \w+$/i}
  # Format : Nom de rue, numéro, ville, code postal, pays
  # TODO: Revoir ce regex
  validates :price_per_hour, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  has_many :cars, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true
  validates :email, format: URI::MailTo::EMAIL_REGEXP
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :devise_controller?
  include Pundit::Authorization
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end



  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end

  private
  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

    # Store the last URL if it is a GET request and not a Devise route
  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  def index
    @bookings = policy_scope(Booking) # Booking.where(user_id: params[:user_id])
  end

  def show
  end

  def new
    @user = User.find(params[:user_id])
    @car = Car.find(params[:car_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    start_date, end_date = params[:booking][:start_date].split(" to ")
    @booking = Booking.new(booking_params.merge(start_date: start_date, end_date: end_date))
    @booking.user = current_user
    @car = Car.find(params[:car_id])
    authorize @booking
    if @booking.save
      redirect_to user_bookings_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @car = Car.find(params[:car_id])
  end

  def update
    start_date, end_date = params[:booking][:start_date].split(" to ")
    @booking.update(booking_params.merge(start_date: start_date, end_date: end_date))
    redirect_to user_car_bookings_path(current_user), flash: { notice: "Booking succesfully updated" }
  end

  def destroy
    @booking.user = current_user
    @booking.destroy
    redirect_to user_bookings_path(current_user), flash: { notice: "Booking succesfully deleted" }, status: :see_other
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:user_id, :car_id, :start_date, :end_date)
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  def index
    @cars = policy_scope(Car)
  end

  def show
    @markers = [{
      lat: @car.latitude,
      lng: @car.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { car: @car }),
  }]
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    authorize @car
    if @car.save

      redirect_to car_path(@car)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to @car, notice: 'Car was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path, notice: 'Car was successfully destroyed.'
  end

  def search
    authorize Car
    Rails.logger.debug "Search Params: #{params.inspect}"

    # Start with all cars
    @cars = Car.all
    Rails.logger.debug "Initial Cars: #{@cars.inspect}"

    # Filter by car type
    if params[:car_type].present?
      @cars = @cars.where(category: params[:car_type])
      Rails.logger.debug "Filtered by car_type: #{@cars.inspect}"
    end

    # Filter by address and radius
    if params[:address].present? && params[:radius].present?
      begin
        @cars = @cars.near(params[:address], params[:radius].to_i)
        Rails.logger.debug "Filtered by address and radius: #{@cars.inspect}"
      rescue => e
        Rails.logger.error "Geocoding error: #{e.message}"
      end
    end

    # Filter by price range
    if params[:price_min].present? || params[:price_max].present?
      price_min = params[:price_min].to_i
      price_max = params[:price_max].to_i
      @cars = @cars.where(price_per_hour: price_min..price_max) if price_min > 0 || price_max > 0
      Rails.logger.debug "Filtered by price range: #{@cars.inspect}"
    end

    Rails.logger.debug "Final Cars: #{@cars.inspect}"

    # Render the index view with the filtered cars
    render :index
  end

  private

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end

  def car_params
    params.require(:car).permit(:address, :brand, :category, :model, :price_per_hour, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  skip_after_action :verify_authorized
  skip_after_action :verify_policy_scoped
  def home
    Rails.logger.debug "Rendering home without Pundit verification"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
  def user_owns_car?(user)
    user.cars.exists?
  end
end

app/views/bookings/edit.html.erb
<%= simple_form_for([@user, @car, @booking]) do |f| %>
  <%= f.input :start_date,
            label: "Change dates",
            as: :string,
            input_html: { data: { controller: "datepicker" },
                          value: "#{@booking.start_date} to #{@booking.end_date}"
            } %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :car_id, value: @car.id %>
  <%= f.submit "Update booking" %>
<% end %>
<%= link_to "Back", user_bookings_path(current_user) %>

app/views/bookings/index.html.erb
<h1>Welcome on your bookings page!</h1>

<div class="container">
  <% @bookings.each do |booking| %>
  <div class="car-title mt-5">
    <h1><%= booking.car.brand %> <%= booking.car.model %></h1>
  </div>
    <ul>
      <li><%= booking.start_date %> to <%= booking.end_date %></li>
      <li><%= booking.car.price_per_hour %> $/h</li>
    </ul>
    <%= link_to "See booking", user_car_booking_path(current_user, id: booking.id, car_id: booking.car) %>
    <%= link_to "Edit booking", edit_user_car_booking_path(current_user, id: booking.id, car_id: booking.car)  %>
    <%= link_to "Delete booking", user_car_booking_path(current_user, booking.car, booking), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container mt-5">
  <h2><strong>Your Booking</strong></h2>
  <div class="row">
    <div class="justify-center align-self-stretch">
      <%= simple_form_for([@user, @car, @booking]) do |f| %>
        <%= f.input :start_date,
                  label: "Select dates",
                  as: :string,
                  input_html: { data: { controller: "datepicker" }} %>
        <%= f.hidden_field :user_id, value: current_user.id %>
         <%= f.hidden_field :car_id, value: @car.id %>
        <%= f.submit "Create booking" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container mt-3">
  <%= link_to "Back to car detail", car_path(id: params[:car_id]), class: "btn btn-primary" %>
  <%= link_to "Back to cars", cars_path, class: "btn btn-primary" %>
</div>

app/views/bookings/show.html.erb
<div class="car-title">
  <h1><%= @booking.car.brand %> <%= @booking.car.model %></h1>
</div>
<ul>
  <li><%= @booking.start_date %> to <%= @booking.end_date %></li>
  <li><%= @booking.car.price_per_hour %> $/h</li>
</ul>

<%= link_to "Edit booking", edit_user_car_booking_path(current_user, id: @booking.id, car_id: @booking.car)  %>
<%= link_to "Back", user_bookings_path(current_user)  %>
<%= link_to "Delete booking", user_car_booking_path(current_user, @booking.car, @booking), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>

app/views/cars/_create_form.html.erb
<%= simple_form_for [current_user, car] do |f| %>
  <%= f.input :brand %>
  <%= f.input :model %>
  <%= f.input :category %>
  <%= f.input :address %>
  <%= f.input :price_per_hour, as: :integer %>
  <%= f.button :submit %>
<% end %>

app/views/cars/_edit_form.html.erb
<%= simple_form_for [current_user, @car] do |f| %>
 <%= f.input :brand %>
 <%= f.input :model %>
 <%= f.input :category %>
 <%= f.input :address %>
 <%= f.input :price_per_hour, as: :integer %>
 <%= f.button :submit, "Update Car" %>
<% end %>

app/views/cars/_info_window.html.erb
<div class="info-window">
  <h2><%= car.brand %> <%= car.model %></h2>
  <p><%= car.address %></p>
</div>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars#destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/edit.html.erb
<h1>Edit Car Details</h1>
<%= render "edit_form", car: @car %>

app/views/cars/index.html.erb
<div class="container">
  <% if @cars.any? %>
    <div class="cover mb-4 d-flex align-items-center justify-content-center">
        <%= render 'shared/searchbar' %>
    </div>
      <div class="row justify-content-center">
        <% @cars.each do |car| %>
          <div class="col-md-3 border p-3">
            <p><strong>Brand:</strong> <%= car.brand %></p>
            <p><strong>Type:</strong> <%= car.category %></p>
            <p><strong>Model:</strong> <%= car.model %></p>
            <p><strong>Price per hour:</strong> <%= car.price_per_hour %>$/h</p>

                <div class="d-flex gap-2">
                <p><%= link_to "More info", car_path(car.id), class: "btn btn-primary" %>
                <p>
                  <%= link_to "Book this car",
                                current_user ? new_user_car_booking_path(current_user, car, @booking) : new_user_session_path,
                                class: "btn btn-primary" %>
                </p>
              </div>
            </div>

        <% end %>
      </div>
  <% else %>
    <p>No cars match your search criteria.</p>
  <% end %>
</div>


<% if policy(Car).new? %>
  <%= link_to "Add a new car", new_user_car_path(current_user), class: "btn btn-primary" %>
<% end %>

app/views/cars/new.html.erb
<h1>Create A New Car</h1>

<%= render  "create_form", car: @car %>

app/views/cars/show.html.erb
<div class="container mt-4">
 <div class="row">
   <div class="col-6">
     <div class="card">
       <% if @car.photos.attached? %>
         <%= image_tag @car.photos.first, class: "card-img-top" %>
       <% end %>

       <div class="card-body">
         <h2 class="card-title"><%= @car.brand %> <%= @car.model %></h2>

         <div class="car-info">
           <p><strong>Category:</strong> <%= @car.category %></p>
           <p><strong>Price per hour:</strong> <%= number_to_currency(@car.price_per_hour) %></p>
           <p><strong>Location:</strong> <%= @car.address %></p>
           <p><strong>Owner:</strong> <%= @car.user.first_name %> <%= @car.user.last_name %></p>
         </div>

         <%= link_to "Book this car",
                          current_user ? new_user_car_booking_path(current_user, @car) : new_user_session_path,
                          class: "btn btn-primary" %>
         <% if policy(@car).edit? %>
           <%= link_to "Edit this car", edit_user_car_path(@car), class: "btn btn-warning d-inline-block" %>
         <% end %>
          <% if policy(@car).destroy? %>
            <%= link_to "Delete this car",
                        car_path(@car),
                        data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                        class: "btn btn-danger d-inline-block" %>
         <% end %>
         <%= link_to "Back to cars", cars_path, class: "btn btn-secondary d-inline-block ms-2" %>
       </div>
     </div>
   </div>

   <div class="col-6">
     <div class="map" style="height: 600px;"
       data-controller="map"
       data-map-markers-value="<%= @markers.to_json %>"
       data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
   </div>
 </div>
</div>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HiryTeamCarbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/searchbar' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="container">
      <%= form_with(url: search_cars_path, method: :get, local: true) do |f| %>
        <div>
          <label for="car_type">Car Type</label>
          <%= f.select :car_type, ['Coupe', 'Convertible', 'Hatchback', 'Sedan', 'SUV', 'Truck', 'Van'], include_blank: 'Choose...' %>
        </div>
        <div>
          <label for="address">Address</label>
          <%= f.text_field :address, placeholder: 'Enter a location' %>
        </div>
        <div>
          <label for="radius">Radius (miles)</label>
          <%= f.select :radius, [5, 10, 20, 500] %>
        </div>
        <div>
          <label for="price_min">From</label>
          <%= f.number_field :price_min, placeholder: 'e.g. 50$' %>
        </div>
        <div>
          <label for="price_max">To</label>
          <%= f.number_field :price_max, placeholder: 'e.g. 100$' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-primary' %>
      <% end %>
</div>